config/routes.rb
Eventer::Application.routes.draw do
  resources :categories

  resources :event_types

  resources :trainers

  resources :events do
    resources :participants
  end

  resources :roles

  devise_for :users
  resources :users

  match 'dashboard' => 'dashboard#index'
  match 'dashboard/pricing' => 'dashboard#pricing'
  match 'dashboard/past_events' => 'dashboard#past_events'
  match 'dashboard/countdown' => 'dashboard#countdown'
  match 'dashboard/funneling' => 'dashboard#funneling'
  match 'dashboard/ratings' => 'dashboard#ratings'
  match 'dashboard/calculate_rating' => 'dashboard#calculate_rating'
  
  match 'api/events' => 'home#index'
  match 'api/trainers' => 'home#trainers'
  match 'api/kleerers' => 'home#kleerers'
  match 'api/community_events' => 'home#index_community'
  match 'api/events/:id' => 'home#show'
  match 'api/event_types' => 'home#event_type_index'
  match 'api/event_types/:id' => 'home#event_type_show'
  match 'api/event_types/:id/trainers' => 'home#show_event_type_trainers'
  match 'api/categories' => 'home#categories'
  
  match 'public_events/:id' => 'public_events#show'
  match 'public_events/:event_id/watch' => 'public_events#watch'
  match 'public_events/:event_id/watch/:participant_id' => 'public_events#watch'
  
  match 'events/update_trainer_select/:id' => 'ajax#events_update_trainer_select'
  match 'events/:id/start_webinar' => 'events#start_webinar'
  match 'events/:id/broadcast_webinar' => 'events#broadcast_webinar'
  match 'events/:id/push_to_crm' => 'events#push_to_crm'
  match 'events/:id/send_certificate' => 'events#send_certificate'
  
  match 'events/:event_id/participant_confirmed' => 'participants#confirm'
  match 'events/:event_id/participants/:id/certificate' => 'participants#certificate'
  match 'events/:event_id/participants_print' => 'participants#print'
  match 'events/:event_id/participants_survey' => 'participants#survey'
  match 'events/:event_id/participants_batch_load' => 'participants#batch_load'
      

  root :to => 'dashboard#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :roles
  
  # Include default devise modules. Others available are:
  # :registerable, :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role_ids
  
  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :activate_menu
  load_and_authorize_resource
    
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
  private
  
  def activate_menu
    @active_menu = "users"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.haml
= form_for @user do |f|
  -if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  %h3 Roles
  - for role in Role.find(:all)
    %div
      = check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role)
      = role.name
  .actions
    = f.submit 'Save'

app/views/users/_new_form.html.haml
= semantic_form_for @user do |f|
  - f.inputs :users_details do
    .grid_12
      = f.input :email, :input_html => { :size => 40 }
      = f.input :password
      = f.input :password_confirmation
    Roles
    - for role in Role.find(:all)
      %div
        = check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role)
        = role.name
    %p
    = f.actions
    = link_to t('formtastic.actions.cancel'), trainers_path

app/views/users/edit.html.haml
.page-header
  %h1.pull-left
    %i.icon-user
    %span Usuarios

= render '/commons/not_migrated_yet'

= render 'edit_form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
.page-header
  %h1.pull-left
    %i.icon-user
    %span Usuarios

= render '/commons/not_migrated_yet'

%p.record-actions
  = link_to t('formtastic.actions.new'), new_user_path

%table
  %tr
    %th= t('formtastic.labels.user.email')
    %th= t('formtastic.labels.user.roles')
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.email
      %td
        - for role in user.roles
          = role.name
          %br
      %td= link_to t('formtastic.actions.view'), user
      %td= link_to t('formtastic.actions.edit'), edit_user_path(user)
      %td= link_to t('formtastic.actions.destroy'), user, :confirm => 'Are you sure?', :method => :delete

app/views/users/new.html.haml
.page-header
  %h1.pull-left
    %i.icon-user
    %span Usuarios

= render '/commons/not_migrated_yet'

= render 'new_form'

app/views/users/show.html.haml
.page-header
  %h1.pull-left
    %i.icon-user
    %span Usuarios

= render '/commons/not_migrated_yet'

%p
  %b Email:
  = @user.email

%h3 Roles
- for role in @user.roles
  %div= role.name

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path