config/routes.rb
Eventer::Application.routes.draw do
  resources :categories

  resources :event_types

  resources :trainers

  resources :events do
    resources :participants
  end

  resources :roles

  devise_for :users
  resources :users

  match 'dashboard' => 'dashboard#index'
  match 'dashboard/pricing' => 'dashboard#pricing'
  match 'dashboard/past_events' => 'dashboard#past_events'
  match 'dashboard/countdown' => 'dashboard#countdown'
  match 'dashboard/funneling' => 'dashboard#funneling'
  match 'dashboard/ratings' => 'dashboard#ratings'
  match 'dashboard/calculate_rating' => 'dashboard#calculate_rating'
  
  match 'api/events' => 'home#index'
  match 'api/trainers' => 'home#trainers'
  match 'api/kleerers' => 'home#kleerers'
  match 'api/community_events' => 'home#index_community'
  match 'api/events/:id' => 'home#show'
  match 'api/event_types' => 'home#event_type_index'
  match 'api/event_types/:id' => 'home#event_type_show'
  match 'api/event_types/:id/trainers' => 'home#show_event_type_trainers'
  match 'api/categories' => 'home#categories'
  
  match 'public_events/:id' => 'public_events#show'
  match 'public_events/:event_id/watch' => 'public_events#watch'
  match 'public_events/:event_id/watch/:participant_id' => 'public_events#watch'
  
  match 'events/update_trainer_select/:id' => 'ajax#events_update_trainer_select'
  match 'events/:id/start_webinar' => 'events#start_webinar'
  match 'events/:id/broadcast_webinar' => 'events#broadcast_webinar'
  match 'events/:id/push_to_crm' => 'events#push_to_crm'
  match 'events/:id/send_certificate' => 'events#send_certificate'
  
  match 'events/:event_id/participant_confirmed' => 'participants#confirm'
  match 'events/:event_id/participants/:id/certificate' => 'participants#certificate'
  match 'events/:event_id/participants_print' => 'participants#print'
  match 'events/:event_id/participants_survey' => 'participants#survey'
  match 'events/:event_id/participants_batch_load' => 'participants#batch_load'
      

  root :to => 'dashboard#index'

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :activate_menu
  load_and_authorize_resource
  
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end
  
  private
  
  def activate_menu
    @active_menu = "roles"
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.haml
= semantic_form_for @role do |f|
  - f.inputs :role_details do
    .grid_12
      = f.input :name, :input_html => { :size => 40 }
      = f.actions
      = link_to t('formtastic.actions.cancel'), roles_path

app/views/roles/edit.html.haml
.page-header
  %h1.pull-left
    %i.icon-cogs
    %span Roles

= render '/commons/not_migrated_yet'

= render 'form'

app/views/roles/index.html.haml
.page-header
  %h1.pull-left
    %i.icon-cogs
    %span Roles

= render '/commons/not_migrated_yet'

%p.record-actions
  = link_to t('formtastic.actions.new'), new_role_path

%table
  %tr
    %th= t('formtastic.labels.role.name')
    %th
    %th
    %th

  - @roles.each do |role|
    %tr
      %td= role.name
      %td= link_to t('action.link.role.show'), role
      %td= link_to t('action.link.role.edit'), edit_role_path(role)
      %td= link_to t('action.link.role.destroy'), role, :confirm => 'Are you sure?', :method => :delete

app/views/roles/new.html.haml
.page-header
  %h1.pull-left
    %i.icon-cogs
    %span Roles

= render '/commons/not_migrated_yet'

= render 'form'

app/views/roles/show.html.haml
.page-header
  %h1.pull-left
    %i.icon-cogs
    %span Roles

= render '/commons/not_migrated_yet'

%p#notice= notice

%p
  %b Name:
  = @role.name

= link_to 'Edit', edit_role_path(@role)
\|
= link_to 'Back', roles_path