config/routes.rb
Eventer::Application.routes.draw do
  resources :categories

  resources :event_types

  resources :trainers

  resources :events do
    resources :participants
  end

  resources :roles

  devise_for :users
  resources :users

  match 'dashboard' => 'dashboard#index'
  match 'dashboard/pricing' => 'dashboard#pricing'
  match 'dashboard/past_events' => 'dashboard#past_events'
  match 'dashboard/countdown' => 'dashboard#countdown'
  match 'dashboard/funneling' => 'dashboard#funneling'
  match 'dashboard/ratings' => 'dashboard#ratings'
  match 'dashboard/calculate_rating' => 'dashboard#calculate_rating'
  
  match 'api/events' => 'home#index'
  match 'api/trainers' => 'home#trainers'
  match 'api/kleerers' => 'home#kleerers'
  match 'api/community_events' => 'home#index_community'
  match 'api/events/:id' => 'home#show'
  match 'api/event_types' => 'home#event_type_index'
  match 'api/event_types/:id' => 'home#event_type_show'
  match 'api/event_types/:id/trainers' => 'home#show_event_type_trainers'
  match 'api/categories' => 'home#categories'
  
  match 'public_events/:id' => 'public_events#show'
  match 'public_events/:event_id/watch' => 'public_events#watch'
  match 'public_events/:event_id/watch/:participant_id' => 'public_events#watch'
  
  match 'events/update_trainer_select/:id' => 'ajax#events_update_trainer_select'
  match 'events/:id/start_webinar' => 'events#start_webinar'
  match 'events/:id/broadcast_webinar' => 'events#broadcast_webinar'
  match 'events/:id/push_to_crm' => 'events#push_to_crm'
  match 'events/:id/send_certificate' => 'events#send_certificate'
  
  match 'events/:event_id/participant_confirmed' => 'participants#confirm'
  match 'events/:event_id/participants/:id/certificate' => 'participants#certificate'
  match 'events/:event_id/participants_print' => 'participants#print'
  match 'events/:event_id/participants_survey' => 'participants#survey'
  match 'events/:event_id/participants_batch_load' => 'participants#batch_load'
      

  root :to => 'dashboard#index'

end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
  belongs_to :country  
  has_and_belongs_to_many :event_types
  has_many :events
  has_many :participants, :through => :events
  
  scope :kleerer, where(:is_kleerer => true)
  
  validates :name, :presence => true
  
  def gravatar_picture_url
    hash = "asljasld"
    hash = Digest::MD5.hexdigest(self.gravatar_email) unless self.gravatar_email.nil?
    "http://www.gravatar.com/avatar/#{hash}"
  end
  
  def to_xml( options )
    super( options.merge(:methods =>  :gravatar_picture_url ) )
  end
    
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :activate_menu
  load_and_authorize_resource
  
  
  # GET /trainers
  # GET /trainers.json
  def index
    @trainers = Trainer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trainers }
    end
  end

  # GET /trainers/1
  # GET /trainers/1.json
  def show
    @trainer = Trainer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trainer }
    end
  end

  # GET /trainers/new
  # GET /trainers/new.json
  def new
    @trainer = Trainer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trainer }
    end
  end

  # GET /trainers/1/edit
  def edit
    @trainer = Trainer.find(params[:id])
  end

  # POST /trainers
  # POST /trainers.json
  def create
    @trainer = Trainer.new(params[:trainer])

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to trainers_path, notice: t('flash.trainer.create.success') }
        format.json { render json: @trainer, status: :created, location: @trainer }
      else
        format.html { render action: "new" }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trainers/1
  # PUT /trainers/1.json
  def update
    @trainer = Trainer.find(params[:id])

    respond_to do |format|
      if @trainer.update_attributes(params[:trainer])
        format.html { redirect_to trainers_path, notice: t('flash.trainer.update.success') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainers/1
  # DELETE /trainers/1.json
  def destroy
    @trainer = Trainer.find(params[:id])
    @trainer.destroy

    respond_to do |format|
      format.html { redirect_to trainers_url, notice: t('flash.trainer.remove.success') }
      format.json { head :no_content }
    end
  end
  
  private
  
  def activate_menu
    @active_menu = "trainers"
  end
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/trainers/_form.html.haml
- @trainer.errors.full_messages.each do |msg|
  .alert.alert-error
    %a.close{ "data-dismiss" => :alert, :href => "#" } &times;
    =msg

.row-fluid
  .span12.box
    .box-header.red-background
      .title
        .icon-edit
          = @trainer.name.nil? ? t("formtastic.labels.trainer.new_title") : @trainer.name
    .box-content
      = form_for @trainer do |f|
        %fieldset.inputs
          .row-fluid
            .span8
              .control-group
                %label.control-label{ :for => :name }= t("formtastic.labels.trainer.name") + " (*)"
                = f.text_field :name, :class => 'input-xxlarge'
          .row-fluid
            .span6
              .control-group
                %label.control-label{ :for => :bio }= t("formtastic.labels.trainer.bio") + " (*)"
                = f.text_area :bio, :rows => 8, :class => "input-block-level"
                %small.muted 
                  Este texto soporta 
                  %a{ :href => "https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet", :target => "_blank"}Markdown 
                  y HTML.
          .row-fluid
            .span6
              .control-group
                %label.control-label{ :for => :bio_en }= t("formtastic.labels.trainer.bio_en") + " (*)"
                = f.text_area :bio_en, :rows => 8, :class => "input-block-level"
                %small.muted 
                  Este texto soporta 
                  %a{ :href => "https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet", :target => "_blank"}Markdown 
                  y HTML.
          .row-fluid
            .span8
              .control-group
                %label.control-label{ :for => :gravatar_email }= t("formtastic.labels.trainer.gravatar_email")
                = f.text_field :gravatar_email
          .row-fluid
            .span8
              .control-group
                %label.control-label{ :for => :twitter_username }= t("formtastic.labels.trainer.twitter_username")
                = f.text_field :twitter_username
          .row-fluid
            .span8
              .control-group
                %label.control-label{ :for => :linkedin_url }= t("formtastic.labels.trainer.linkedin_url")
                = f.text_field :linkedin_url
          .row-fluid
            .span8
              .control-group
                %label.control-label{ :for => :tag_name }= t("formtastic.labels.trainer.tag_name")
                = f.text_field :tag_name
          .row-fluid
            .span8
              .control-group
                %label.control-label{ :for => :signature_image }= t("formtastic.labels.trainer.signature_image")
                = f.text_field :signature_image
          .row-fluid
            .span8
              .control-group
                %label.control-label{ :for => :signature_credentials }= t("formtastic.labels.trainer.signature_credentials")
                = f.text_field :signature_credentials
          .row-fluid
            .span3
              .control-group
                %label.control-label{ :for => :is_kleerer }= t("formtastic.labels.category.is_kleerer")
                = f.check_box :is_kleerer
          .row-fluid
            .span12
              .control-group
                %label.control-label{ :for => :country_id } País
                = f.collection_select :country_id, Country.find(:all).sort{|p1,p2| p1.name <=> p2.name}, :id, :name, {include_blank: 'Selecciona uno...'}

          .row-fuid
            .span12
              .form-actions
                .text-right
                  %button.btn.btn-primary.btn-large{:id => "guardar", :name => "commit", :type => "submit"}
                    %i.icon-save
                    Guardar
                  %a.btn.btn-large{ :href => categories_path }
                    %i.icon-undo
                    Cancelar

app/views/trainers/edit.html.haml
.page-header
  %h1.pull-left
    %i.icon-briefcase
    %span Entrenadores

= render 'form'

app/views/trainers/index.html.haml
.page-header
  %h1.pull-left
    %i.icon-briefcase
    %span Entrenadores

= render '/commons/not_migrated_yet'


%p.record-actions
  = link_to t('formtastic.actions.new'), new_trainer_path

%table
  %tr
    %th= t('formtastic.labels.name')
    %th.record-actions
   
  - @trainers.each do |trainer|
    %tr
      %td= link_to trainer.name, trainer
      %td.record-actions
        = link_to t('formtastic.actions.view'), trainer
        = link_to t('formtastic.actions.edit'), edit_trainer_path(trainer)
        = link_to t('formtastic.actions.destroy'), trainer, :confirm => t('confirm.sure'), :method => :delete

app/views/trainers/new.html.haml
.page-header
  %h1.pull-left
    %i.icon-briefcase
    %span Entrenadores

= render 'form'

app/views/trainers/show.html.haml
.page-header
  %h1.pull-left
    %i.icon-briefcase
    %span Entrenadores

= render '/commons/not_migrated_yet'


%p
  %b= t('formtastic.labels.name') + ": "
  = @trainer.name
  %b= t('formtastic.labels.bio') + ": "
  = @trainer.bio
  %b= t('formtastic.labels.trainer.bio_en') + ": "
  = @trainer.bio_en
  %b= t('formtastic.labels.trainer.linkedin_url') + ": "
  = @trainer.linkedin_url
  %b= t('formtastic.labels.trainer.twitter_username') + ": "
  = @trainer.twitter_username
  %b= t('formtastic.labels.trainer.is_kleerer') + ": "
  = @trainer.is_kleerer
  %b= t('formtastic.labels.trainer.gravatar_email') + ": "
  = @trainer.gravatar_email
  %b= t('formtastic.labels.trainer.gravatar_picture') + ": "
  = @trainer.gravatar_picture_url

= link_to t('formtastic.actions.edit'), edit_trainer_path(@trainer)
\|
= link_to t('formtastic.actions.cancel'), trainers_path